FROM ubuntu
RUN apt update
RUN apt install apache2 -y
RUN apt install iputils-ping -y
RUN apt install net-tools -y
RUN mkdir /userdata
RUN echo "Hello user :)" > /userdata/message.txt
ENTRYPOINT ["apachectl","-D","FOREGROUND"]
EXPOSE 80
ENV name="developer"
